# Generated by Django 3.2 on 2021-04-15 22:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='board',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
