# Generated by Django 3.2 on 2021-04-16 05:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210415_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.BinaryField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='bg',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='board.image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='board.image'),
        ),
    ]
