# Generated by Django 3.2 on 2021-04-16 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210416_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='bg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.image'),
        ),
    ]
