# Generated by Django 3.2 on 2021-04-17 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20210416_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
